#!/usr/bin/env node
/* ============================================================================
   tdd-toolkit init — drop the TDD Toolkit into any Next.js (App Router) project
   ----------------------------------------------------------------------------
   Usage (from a target project root):

     node path/to/Tdd/scripts/init.mjs [--src-dir <dir>] [--alias @] [--yes]

   or, once published, `npx @you/tdd-toolkit init`.

   It does three things, all idempotent:
     1. Copies the component folder        → <srcRoot>/components/Tdd
     2. Scaffolds the three API routes      → <appRoot>/__tdd/{run,screenshot,snippets}/route.ts
     3. Prints the remaining manual steps   (mount <TddToolkit/>, optional installs)

   It NEVER runs `npm install` for you silently. Instead it tells you exactly
   which packages to add and why — because a React component must not install
   packages, but a CLI you ran on purpose can tell you what to install.
   ========================================================================== */

import { cp, mkdir, writeFile, readFile, access, readdir } from "node:fs/promises";
import { constants } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import process from "node:process";

const TOOLKIT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CWD = process.cwd();

/* ---- tiny arg parser ---------------------------------------------------- */
function parseArgs(argv) {
  const args = { alias: "@", yes: false, srcDir: undefined };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--yes" || a === "-y") args.yes = true;
    else if (a === "--alias") args.alias = argv[++i] ?? "@";
    else if (a === "--src-dir") args.srcDir = argv[++i];
    else if (a === "init") {
      /* allow `init` as a positional verb */
    } else if (a.startsWith("--")) {
      console.warn(`Unknown flag: ${a}`);
    }
  }
  return args;
}

async function exists(p) {
  try {
    await access(p, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

/* ---- locate the target project's app/ and components root --------------- */
/** Next.js App Router lives in either `app/` or `src/app/`. Detect which. */
async function detectLayout(explicitSrcDir) {
  if (explicitSrcDir) {
    return { srcRoot: path.join(CWD, explicitSrcDir), label: explicitSrcDir + "/" };
  }
  if (await exists(path.join(CWD, "src", "app"))) {
    return { srcRoot: path.join(CWD, "src"), label: "src/" };
  }
  if (await exists(path.join(CWD, "app"))) {
    return { srcRoot: CWD, label: "" };
  }
  return null;
}

/* ---- route stubs -------------------------------------------------------- */
/* Each route re-exports the handler logic from the copied component folder, so
   there is no duplicated logic to drift. The alias (default "@") must resolve
   to <srcRoot>; if the target uses a different alias, pass --alias. */
function routeStub(alias, modulePath, exportsList) {
  return `/* Auto-generated by tdd-toolkit init. Dev-only TDD Toolkit bridge route.
   The handler logic lives in the copied component folder; this file just wires
   it into the App Router. Safe to commit. */
export { ${exportsList} } from "${alias}/components/Tdd/server/${modulePath}";
export const runtime = "nodejs";
export const dynamic = "force-dynamic";
`;
}

const ROUTES = [
  { dir: "run", module: "run", exports: "POST, GET" },
  { dir: "screenshot", module: "screenshot", exports: "POST, GET" },
  { dir: "snippets", module: "snippets", exports: "GET, POST, DELETE" },
];

async function main() {
  const args = parseArgs(process.argv.slice(2));

  console.log("\n  TDD Toolkit installer\n  ─────────────────────");

  const layout = await detectLayout(args.srcDir);
  if (!layout) {
    console.error(
      "\n  ✖ Could not find an App Router directory (looked for ./app and ./src/app).\n" +
        "    Run this from your Next.js project root, or pass --src-dir <dir>.\n"
    );
    process.exit(1);
  }

  const componentsDest = path.join(layout.srcRoot, "components", "Tdd");
  const appRoot = path.join(layout.srcRoot, "app");

  /* 1. copy the component folder. We keep scripts/copy-monaco.mjs (the install
        instructions reference it) but drop init.mjs — the installer shouldn't
        ship inside installed projects. */
  console.log(`\n  • Copying component → ${path.relative(CWD, componentsDest)}`);
  if ((await exists(componentsDest)) && !args.yes) {
    console.log(
      `    (already exists — re-run with --yes to overwrite; skipping copy)`
    );
  } else {
    await mkdir(path.dirname(componentsDest), { recursive: true });
    await cp(TOOLKIT_DIR, componentsDest, {
      recursive: true,
      filter: (src) => path.basename(src) !== "init.mjs",
    });
    console.log("    ✓ copied");
  }

  /* 2. scaffold the three routes. */
  console.log(`\n  • Scaffolding routes → ${path.relative(CWD, path.join(appRoot, "__tdd"))}/`);
  for (const r of ROUTES) {
    const dir = path.join(appRoot, "__tdd", r.dir);
    const file = path.join(dir, "route.ts");
    if ((await exists(file)) && !args.yes) {
      console.log(`    (skip ${r.dir}/route.ts — exists)`);
      continue;
    }
    await mkdir(dir, { recursive: true });
    await writeFile(file, routeStub(args.alias, r.module, r.exports), "utf8");
    console.log(`    ✓ __tdd/${r.dir}/route.ts`);
  }

  /* 3. final instructions. */
  const hasMonaco = await dependencyPresent("monaco-editor");
  const hasPlaywright = await dependencyPresent("playwright");

  console.log("\n  Next steps");
  console.log("  ──────────");
  console.log("  1. Mount the overlay in your root layout (dev-only by design):");
  console.log("");
  console.log(`       import { TddToolkit } from "${args.alias}/components/Tdd";`);
  console.log("       // …inside <body>:  <TddToolkit />");
  console.log("");
  console.log(`  2. Make sure your tsconfig "paths" maps "${args.alias}/*" → "${layout.label}*".`);

  const installs = [];
  if (!hasMonaco) installs.push("monaco-editor            # local code editor (else falls back to a CDN)");
  if (!hasPlaywright)
    installs.push("playwright @playwright/test  # optional: the Playwright bridge runner");

  if (installs.length) {
    console.log("\n  3. Optional packages (the in-page runner works without ANY of these):");
    console.log("");
    console.log("       npm i -D " + installs.map((s) => s.split(" ")[0]).join(" "));
    for (const line of installs) console.log("         " + line);
    if (!hasPlaywright) {
      console.log("\n     If you install Playwright, also fetch the browser:");
      console.log("       npx playwright install chromium");
    }
    if (!hasMonaco) {
      console.log("\n     After installing monaco-editor, vendor it for offline use:");
      console.log("       node components/Tdd/scripts/copy-monaco.mjs");
    }
  } else {
    console.log("\n  3. All optional deps already present — nothing else to install. 🎉");
  }

  console.log("");
}

/** Is a package resolvable from the target project? */
async function dependencyPresent(name) {
  // Cheap check: look in the target's node_modules and package.json.
  if (await exists(path.join(CWD, "node_modules", name, "package.json"))) return true;
  try {
    const pkg = JSON.parse(await readFile(path.join(CWD, "package.json"), "utf8"));
    return Boolean(
      pkg.dependencies?.[name] ||
        pkg.devDependencies?.[name] ||
        pkg.optionalDependencies?.[name]
    );
  } catch {
    return false;
  }
}

main().catch((err) => {
  console.error(`\n  ✖ init failed: ${err?.stack ?? err}\n`);
  process.exit(1);
});
